version: '3.8'
services:
    php-apache:
        container_name: php-apache
        build:
            context: ./
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./src:/var/www/html/
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: q1w2e3r4
        ports:
            - "9906:3306"
    redis:
        image: redis
        container_name: redis
        ports:
          - "6382:6379"